# Generated by Django 2.2.12 on 2020-04-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200411_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userupdate',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userupdate',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='donation_list',
            name='user',
        ),
    ]
