# Generated by Django 2.2.12 on 2020-04-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200411_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userupdate',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='userupdate',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
