# Generated by Django 2.2.12 on 2020-04-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200411_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_list',
            name='quantitiy',
        ),
        migrations.AlterField(
            model_name='donation_list',
            name='items',
            field=models.TextField(),
        ),
    ]
